sudo: false
dist: trusty
language: python

python:
  - "3.5"
  - "3.6"

env:
  - DJANGO="1.11"
  - DJANGO="2.0"

services:
  - postgresql

addons:
  postgresql: "9.5"

install: pip install tox-travis coverage
script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
