version: "3.7"
services:
  python:
    build:
      context: .
      dockerfile: .devcontainer/python/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"